[package]
name = "h5_dumper"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
bitflags = "2.6.0"
byteorder = "1.5.0"
flate2 = { version = "1.0.33", features = ["zlib"] }
thiserror = "1.0.63"
